import { Inter } from "next/font/google";
import "./globals.css";
import { DialogProvider } from "@/context/Context";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import Cart from "@/components/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DialogProvider>
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            <Cart />
            {children}
            <Footer />
          </body>
        </html>
      </ClerkProvider>
    </DialogProvider>
  );
}
